### ISSUE TITLE
Only getting  Join not accepted: Denied

### ISSUE THREAD

**Issue by Nighter3D** [YourproductSmarter/KISSLoRa-demo#2]
Hello. Im trying to get the KissLoRa badge working at home. I turned it one, but it doesn't really do anything anymore. Ive hooked it onto serial and i get this:

> --- Resetting RN module
> Model: RN2483
> Version: 1.0.1
> Sending: mac set deveui 0004A30B001F8135
> Sending: mac set adr off
> --- Random Seed
> -- hwEui read from module: 0004A30B001F8135
> -- seed: 21272
> --- I2C Accelerometer initialized
> Sending: mac set rx2 3 869525000
> Sending: mac set ch drrange 1 0 6
> Sending: mac set ch dcycle 0 799
> Sending: mac set ch dcycle 1 799
> Sending: mac set ch dcycle 2 799
> Sending: mac set ch dcycle 3 799
> Sending: mac set ch freq 3 867100000
> Sending: mac set ch drrange 3 0 5
> Sending: mac set ch status 3 on
> Sending: mac set ch dcycle 4 799
> Sending: mac set ch freq 4 867300000
> Sending: mac set ch drrange 4 0 5
> Sending: mac set ch status 4 on
> Sending: mac set ch dcycle 5 799
> Sending: mac set ch freq 5 867500000
> Sending: mac set ch drrange 5 0 5
> Sending: mac set ch status 5 on
> Sending: mac set ch dcycle 6 799
> Sending: mac set ch freq 6 867700000
> Sending: mac set ch drrange 6 0 5
> Sending: mac set ch status 6 on
> Sending: mac set ch dcycle 7 799
> Sending: mac set ch freq 7 867900000
> Sending: mac set ch drrange 7 0 5
> Sending: mac set ch status 7 on
> Sending: mac set pwridx 1
> Sending: mac set retx 7
> Sending: mac set dr 5
> Sending: mac join otaa 
> Join not accepted: denied
> Check your coverage, keys and backend status.
> Sending: mac join otaa 
> Join not accepted: denied
> Check your coverage, keys and backend status.
> Sending: mac join otaa 
> Join not accepted: denied
> Check your coverage, keys and backend status.
> Sending: mac join otaa 
> Response is not OK: no_free_ch
> Send join command failed
> Sending: mac join otaa 
> Response is not OK: no_free_ch
> Send join command failed
> Sending: mac join otaa 
> Response is not OK: no_free_ch
> Send join command failed
> Sending: mac join otaa 
> Response is not OK: no_free_ch
> Send join command failed

So either i get "Join not accepted: denied" or "Response is not OK: no_free_ch"

I am rather new to this so idk if this normal, or if this is a sign that there is no coverage (tough i should be according to LoRa maps) or something else. I also had this when i had restarted it at the convention, had to recommission it after someone re-programmed the firmware for me at one of the commission points.

**Comment by Roos-AID** [comment]
I encounter the same. Should be coverage.  I tried the LoRa_TX_RX sample program, applied my own appEui = "70B3D57Exxxxxxxx"; and appKey  = "2EF8AD9692B8F857AC59264Fxxxxxxx"; (xxxxxxxx to hide my accesscode) from the Things Network Console, then compiled and uploaded. 

I seems that the network does not recognise my device. 

Any clues ?

**Comment by jderriks** [comment]
Mine doesn't work either. Guess there is no Lora gateway in the neighbourhood:
https://www.thethingsnetwork.org/map
Ho can you see gateway connectivity? Is it the blue light?

**Comment by OnnoH** [comment]
I have my own gateway nearby and the Kiss works very nice (factory settings ;-). The blue led flashes at regular intervals indicating LoRa activity.

**Comment by jpmeijers** [comment]
Log onto [The Things Network Console](https://console.thethingsnetwork.org/), go to Applications, choose the *kiss-lora-<your username>* application. 

If you do not see any application listed with a name starting with *kiss-lora-*, it means that you have not commissioned a device at the fair, using your TTN account.

In the top right menu, choose *Devices*. If your device was successfully commissioned at the E&A fair, you should see one device listed with the name *kiss-lora-device-<deveui>*. The last 16 hex characters in the name is the Device EUI of your KISS gadget. You can see this back in the Serial Monitor, like:
`Sending: mac set deveui 0004A30B001F8135`

If you see more than one device listed on the console, it means somehow someone else's gadget was registered on your application. This happened when you clicked on the terminal number on the commissioning app, while someone else's device was still plugged into the commissioning terminal. You can safely delete all devices that are not yours.

If you do not see any device listed, it means that the commissioning process was interrupted.

Click in the device in the list with the same EUI than the EUI of your KISS gadget. In the *Device Overview*, look at *Status*. It should indicate when your device was received by The Things Network for the last time. If it says "never seen", it means that we have not heard your device yet.

Click on the *Data* tab at the top right. This page will show everything that is received and sent to your KISS gadget.

As soon as you see `Sending: mac join otaa` on the serial output, you should also see *Activation* on the Data webpage. If you do not see anything on the Data page, there can be two things wrong:
1. You do not have coverage of The Things Network.
2. During commissioning something went wrong and your device was not successfully programmed with the correct keys to communicate with you application.

Because many of the possible problems are related to a failed commissioning, I will write a document to describe how to commission, or re-commission a device at home. Please keep an eye on the main readme in this repository.

**Comment by jpmeijers** [comment]
To see if you have coverage of The Things Network, you can also have a look at:
http://ttnmapper.org

**Comment by Roos-AID** [comment]
If you check the coverage, please be aware that many gateways are not yet commissioned but planned. 
In my area there is no operational gateway, but many planned, hence I get the failed connection and no free channel error. 

Regards,
Rob

**Comment by MakanMakan83** [comment]
I got the same problem .... I live in Eindhoven and coverage should be good enough .... 
Please help us out ... I really would like to play with the device myself ...

**Comment by tiemekuyper** [comment]
Is there anything else to say about this "Join not accepted: denied" issue? I test here in Eindhoven, 500 meters from the FlightForum gateway, Pretty sure all the AppEUI & AppKey are programmed well, Made the Device at the Console, redone several times... But no success. Did find some issues with capacitors on the gadget, but since I am not far away from the Gateway this is pretty sure not the case. Received my unit later than the Utrecht fair, so I would like to get it commissioned_at_home. Programming goes well using Arduino 1.81 surrounding, but no communication... I have seen the unit working in the very beginning before I reprogrammed. Could it be that the DevEUI can only be used once in the Console? Thanks a lot!

**Comment by thomaswesenberg** [comment]
Issuing a "sys factoryRESET" may help. If you use "mac save" be sure to have valid data for devaddr, appeui and appkey. This project may help too:
https://github.com/thomaswesenberg/LoRaWAN-device-GPS-RaspBerry-Pi

**Comment by Nighter3D** [comment]
> 
> 
> Issuing a "sys factoryRESET" may help. If you use "mac save" be sure to have valid data for devaddr, appeui and appkey. This project may help too:
> https://github.com/thomaswesenberg/LoRaWAN-device-GPS-RaspBerry-Pi

I'll be honest. Device has already broken and sent of to e-waste long ago. After 2 months i just gave up. There just seemed to be no TTN gateways anywhere nearby and i had no intention to set up my own gateway so it was just a useless little circuit. If it was meant to advertise LoraWan, TTN and the Microchip lorawan module it kind of failed it's job.
